### ISSUE TITLE
Improving IactEventListIrf and Iact1dUnbinnedLkl I/O and interface

### ISSUE THREAD

**Issue by cosimoNigro** [javierrico/gLike#23]
The `IactEventListIrf` currently acts as a mere interface between the `gLikeInputs` ROOT files (that are shipped with this repository) and the `Iact1dUnbinnedLkl` analysis class. 
A user cannot produce gLikeInputs himself with the code in this repository. 
More specifically: 

* `IactEventListIrf` misses a `Write()` method to write to disk its output. In PR #24 I am going to show how to define a `IactEventListIrf` object using a `FITS` file I generated with `gammapy`. Once created, I'd like to save it to disk and then to load it in a `Iact1dUnbinnedLkl` object for a likelihood analysis but this is not possible at the moment! 

* Additionally I cannot pass the `IactEventListIrf` instance to the `Iact1dUnbinnedLkl`as no method is given for this. Checking the `Iact1dUnbinnedLkl` setters one can `SetAeff()`, `SetEResoAndBias()`, and `SetObsTime()` but the On and Off event lists cannot be passed.
Indeed in `Iact1dUnbinnedLkl.cc` the IactEventListIrf is directly generated from the `"inputfile="` string (see [see here](https://github.com/javierrico/gLike/blob/master/src/Iact1dUnbinnedLkl.cc#L293)).

Resuming: `Iact1dUnbinnedLkl` reads from disk but `IactEventListIrf` cannot write!
I propose either to add a `Write()` method to `IactEventListIrf`or to add a `SetIactEventListIrf()` method to the `Iact1dUnbinnedLkl`. Or both!

**Comment by cosimoNigro** [comment]
Can I close also this? Now the input for `IactEventListIrf` is separated from `Iact1dUnbinned`

**Comment by javierrico** [comment]
I think so, yes
