### ISSUE TITLE
Remove old MIACTEventListIRF class and convertGLikeInputFiles.C script

### ISSUE THREAD

**Issue by javierrico** [javierrico/gLike#37]
convertGLikeInputFiles. C script was meant to be transitory to allow conversion of old data files into the new format introduced since the migration to gitHub, and the only reason why the old MIACTEventListIRF is still part of the source code
For the next  (ESCAPE WP3 Zenodo)-related release we probably want to consider removing all this.
@cosimoNigro can you please have a look on possible undesirable side-effects? I expect none...

**Comment by dkerszberg** [comment]
I can confirm that deleting include/MIACTEventListIRF.h, scripts/convertGLikeInputFiles.C, src/MIACTEventListIRF.cc and modifying (to remove references to MIACTEventListIRF) include/gLikeLinkDef.h, Makefile and CMakeLists.txt had no effect on compilation and running an analysis.
Additionally any of the previously tagged version can still be used to convert files if needed. So from my side no problem in removing those files.

**Comment by javierrico** [comment]
Ok, thanks, it will be for the next release, since the first Zenodo-ESCAPE one is already out...

**Comment by javierrico** [comment]
With the new imminent release v00.10, this will be solved
