### ISSUE TITLE
gLike installation fails when using cmake

### ISSUE THREAD

**Issue by FrancescoGSaturni** [javierrico/gLike#46]
When trying to compile and install gLike on remote machines that I use for DM analyses, I run into the following errors. Note that on such computers I have:

- Ubuntu 18.04.2 LTS (GNU/Linux 5.3.0-59-generic x86_64) as OS;
- ROOT v5.34.38 working fine;
- root privileges.

If I run the "vanilla" cmake installation of gLike, I get this error here:

_CMake Error at CMakeLists.txt:18 (find_package):_
_By not providing "FindROOT.cmake" in CMAKE_MODULE_PATH this project has_
_asked CMake to find a package configuration file provided by "ROOT", but_
_CMake did not find one._

_Could not find a package configuration file provided by "ROOT" with any of_
_the following names:_

    ROOTConfig.cmake
    root-config.cmake

_Add the installation prefix of "ROOT" to CMAKE_PREFIX_PATH or set_
_"ROOT_DIR" to a directory containing one of the above files.  If "ROOT"_
_provides a separate development package or SDK, be sure it has been_
_installed._

_-- Configuring incomplete, errors occurred!_
_See also "/home/astriteam/gLike/build/CMakeFiles/CMakeOutput.log"._

I found online the suggestion to add the following line to the CMakeLists.txt file:

**set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} $ENV{ROOTSYS}/etc/cmake)**

By adding this, I now get this message:

_CMake Error at CMakeLists.txt:22 (include):_
_include called with wrong number of arguments.  include() only takes one_
_file._

_-- Configuring incomplete, errors occurred!_
_See also "/home/astriteam/gLike/build/CMakeFiles/CMakeOutput.log"._

Commenting out the line:

**include(${ROOT_USE_FILE})**

I get now a successful cmake precompilation, but when I type make I become stuck on this last error:

_make[2]: *** No rule to make target '../linkFile-NOTFOUND', needed by 'gLikeDict.cxx'.  Stop._
_CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/gLike.dir/all' failed_
_make[1]: *** [CMakeFiles/gLike.dir/all] Error 2_
_Makefile:129: recipe for target 'all' failed_
_make: *** [all] Error 2_

Any suggestions on how to proceed are welcome. Many thanks in advance!

**Comment by cosimoNigro** [comment]
Hello @FrancescoGSaturni I think the error might be due to the fact that ROOT itself has to be compiled with `cmake`
Can you take a look at this issue in the ROOT forum? I think I remember there is some specific file generated by the `cmake` compilation of ROOT that are needed to compile another program dependent by it with `cmake`
https://root-forum.cern.ch/t/findroot-cmake-not-found-by-old-5-34-root-versions/40291/7

@javierrico, you had a similar problem right? 
You had to recompile your old root with `cmake` before compiling gLike with `cmake` as well. Is that correct?

**Comment by javierrico** [comment]
Yes, revising our conversation in PR #33, that seems to be the case

**Comment by javierrico** [comment]
Hi @FrancescoGSaturni  and @cosimoNigro 
Is this issue solved? can we close it? cheers

**Comment by FrancescoGSaturni** [comment]
Hi @javierrico,
for the time being I am not personally planning to investigate this issue further due to HW problems on my PC and HW+SW updates on the remote machines which I am working on. Therefore, if you need to close this issue please go on. If needed, I will ask to reopen it when I will be able to come back to it once all the problems on the machines I'm using will be solved.
Best,
FG

**Comment by javierrico** [comment]
Hi @FrancescoGSaturni 
Very good, I close it for the time being and please re-open in case of need
Cheers
