### ISSUE TITLE
Clash between original (pre-cmake) and cmake versions of Makefile

### ISSUE THREAD

**Issue by javierrico** [javierrico/gLike#58]
In order to be able to build the library and executables we still keep the old hand-made Makefile in the repository
However, if we use cmake, such "old" Makefile is overwritten, which generates two potential problems:
- If for some reason I need to alternate between the two building modes I need to recover the original Makefile from gitHub every time I want to use the old way
- After using cmake, git will recognize a new version of the Makefile file, and will suggest to add and commit it

None of these problems are major, and also they will disappear with the next major release when the old way will be deprecated, but I was wondering if there is a simple solution that can fix these two problems for the time being.

**Comment by cosimoNigro** [comment]
Sorry for not replying before, the solution is clearly to eliminate the old Makefile and to add a `Makefile` to the `.gitignore`.
I think the new installation method has been tested enough, no?
@dkerszberg had still some more problems on PIC, but I guess it's because of the antiquated C compilers available.
Anything to comment @dkerszberg?

**Comment by dkerszberg** [comment]
The problem is actually with running the executable with HTCondor, not cmake (that part is fine).

**Comment by javierrico** [comment]
Thanks @cosimoNigro for the reply
One more thing, in principle the cmake should no create any file in the source directory right? just in the build directory.
So the problem I was reporting here is probably just a consequence of me inadvertently defining the build directory as the source directory. That is probably a very bad practice, among other things because then there will be some extra files that git will ask you about. So probably there is nothing to do (not even including Makefile in the .gitignore file), but just building the software right.

**Comment by javierrico** [comment]
> The problem is actually with running the executable with HTCondor, not cmake (that part is fine).

But that is not a problem of the code but of your HTCondor scripts, right?

**Comment by cosimoNigro** [comment]
Hi @javierrico,

yes exactly, `cmake` will read the `CMakeLists.txt` and create the `Makefile` in the same directory where it is run.
And yes I would recommend building in another directory, as I think we already suggest in the instructions.

**Comment by javierrico** [comment]
Thanks, then I think there is no issue, I close it

**Comment by dkerszberg** [comment]
> > The problem is actually with running the executable with HTCondor, not cmake (that part is fine).
> 
> But that is not a problem of the code but of your HTCondor scripts, right?

Yes, the problem is in the config at PIC somewhere. So independent of gLike.
