### ISSUE TITLE
computeCLBands does not read seedtag correctly

### ISSUE THREAD

**Issue by StFroese** [javierrico/gLike#68]
The seedtag is written in the filename with 4 digits:
https://github.com/javierrico/gLike/blob/82fa410b78a2bb5742a581c7e953fb866a3c0f30/exec/jointLklDM.cc#L932

but computeCLBands cannot find the files because it expects no leading zeros

https://github.com/javierrico/gLike/blob/82fa410b78a2bb5742a581c7e953fb866a3c0f30/exec/computeCLBands.cc#L195

This should be changed to 
`TString seedtag  = Form("_%04d",ifile); `

Branch: v00.10 & main

**Comment by javierrico** [comment]
Hi @StFroese 
Thanks for spotting bugs and reporting!
The fix is now included in v00.10 branch and soon will be included in the v00.10.01 release and in the master branch
Cheers

**Comment by StFroese** [comment]
@javierrico No problem, thank you for fixing it!
